version: '3.9'

services:
  web:
    images: ubuntu
  fesacloudserver:
    container_name: fesacloudserver
    build: ./server
    expose:
      - 8000
    volumes:
      - ./server/usr/src/app
  fesacloud:
    container_name: fesacloud
    build: ./client
    expose:
      - 5000
    volumes:
      - ./client:/usr/src/app
  nginx:
    build: ./nginx
    ports:
      - 80:80
    links:
      - fesacloudserver
      - fesacloud
    restart: always